//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Net.Quic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Net.Quic.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only IPv4 or IPv6 are supported.
        /// </summary>
        internal static string net_quic_addressfamily_notsupported {
            get {
                return ResourceManager.GetString("net_quic_addressfamily_notsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remote certificate is invalid because of errors in the certificate chain: {0}.
        /// </summary>
        internal static string net_quic_cert_chain_validation {
            get {
                return ResourceManager.GetString("net_quic_cert_chain_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remote certificate was rejected by the provided RemoteCertificateValidationCallback..
        /// </summary>
        internal static string net_quic_cert_custom_validation {
            get {
                return ResourceManager.GetString("net_quic_cert_custom_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection aborted by peer ({0})..
        /// </summary>
        internal static string net_quic_connectionaborted {
            get {
                return ResourceManager.GetString("net_quic_connectionaborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must pass loopback address and port 0.
        /// </summary>
        internal static string net_quic_noloopback {
            get {
                return ResourceManager.GetString("net_quic_noloopback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection is not connected..
        /// </summary>
        internal static string net_quic_not_connected {
            get {
                return ResourceManager.GetString("net_quic_not_connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUIC is not supported on this platform. See https://aka.ms/dotnetquic.
        /// </summary>
        internal static string net_quic_notsupported {
            get {
                return ResourceManager.GetString("net_quic_notsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation aborted..
        /// </summary>
        internal static string net_quic_operationaborted {
            get {
                return ResourceManager.GetString("net_quic_operationaborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading is not allowed on stream..
        /// </summary>
        internal static string net_quic_reading_notallowed {
            get {
                return ResourceManager.GetString("net_quic_reading_notallowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending has already been aborted on the stream.
        /// </summary>
        internal static string net_quic_sending_aborted {
            get {
                return ResourceManager.GetString("net_quic_sending_aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not supported by Fujin.Net.Quic..
        /// </summary>
        internal static string net_quic_ssl_option {
            get {
                return ResourceManager.GetString("net_quic_ssl_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream aborted by peer ({0})..
        /// </summary>
        internal static string net_quic_streamaborted {
            get {
                return ResourceManager.GetString("net_quic_streamaborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection timed out..
        /// </summary>
        internal static string net_quic_timeout {
            get {
                return ResourceManager.GetString("net_quic_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout can only be set to &apos;System.Threading.Timeout.Infinite&apos; or a value &gt; 0..
        /// </summary>
        internal static string net_quic_timeout_use_gt_zero {
            get {
                return ResourceManager.GetString("net_quic_timeout_use_gt_zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported address family of &apos;{0}&apos; for remote endpoint..
        /// </summary>
        internal static string net_quic_unsupported_address_family {
            get {
                return ResourceManager.GetString("net_quic_unsupported_address_family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing is not allowed on stream..
        /// </summary>
        internal static string net_quic_writing_notallowed {
            get {
                return ResourceManager.GetString("net_quic_writing_notallowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application protocol list is invalid..
        /// </summary>
        internal static string net_ssl_app_protocols_invalid {
            get {
                return ResourceManager.GetString("net_ssl_app_protocols_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fujin.Net.Quic is not supported on this platform..
        /// </summary>
        internal static string SystemNetQuic_PlatformNotSupported {
            get {
                return ResourceManager.GetString("SystemNetQuic_PlatformNotSupported", resourceCulture);
            }
        }
    }
}
